/*! responsive-nav.js v1.0.21 by @viljamis, http://responsive-nav.com, MIT license */
var responsiveNav=function(s,t){window.getComputedStyle||(window.getComputedStyle=function(a){this.el=a;this.getPropertyValue=function(b){var c=/(\-([a-z]){1})/g;"float"===b&&(b="styleFloat");c.test(b)&&(b=b.replace(c,function(a,b,c){return c.toUpperCase()}));return a.currentStyle[b]?a.currentStyle[b]:null};return this});var d,f,e,g=document.createElement("style"),n,p,k=function(a,b,c,d){if("addEventListener"in a)try{a.addEventListener(b,c,d)}catch(e){if("object"===typeof c&&c.handleEvent)a.addEventListener(b,
function(a){c.handleEvent.call(c,a)},d);else throw e;}else"attachEvent"in a&&("object"===typeof c&&c.handleEvent?a.attachEvent("on"+b,function(){c.handleEvent.call(c)}):a.attachEvent("on"+b,c))},h=function(a,b,c,d){if("removeEventListener"in a)try{a.removeEventListener(b,c,d)}catch(e){if("object"===typeof c&&c.handleEvent)a.removeEventListener(b,function(a){c.handleEvent.call(c,a)},d);else throw e;}else"detachEvent"in a&&("object"===typeof c&&c.handleEvent?a.detachEvent("on"+b,function(){c.handleEvent.call(c)}):
a.detachEvent("on"+b,c))},u=function(a){if(1>a.children.length)throw Error("The Nav container has no containing elements");for(var b=[],c=0;c<a.children.length;c++)1===a.children[c].nodeType&&b.push(a.children[c]);return b},l=function(a,b){for(var c in b)a.setAttribute(c,b[c])},m=function(a,b){0!==a.className.indexOf(b)&&(a.className+=" "+b,a.className=a.className.replace(/(^\s*)|(\s*$)/g,""))},q=function(a,b){a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," ").replace(/(^\s*)|(\s*$)/g,
"")},r=function(a,b){var c;this.options={animate:!0,transition:250,label:"Menu",insert:"after",customToggle:"",openPos:"relative",jsClass:"js",init:function(){},open:function(){},close:function(){}};for(c in b)this.options[c]=b[c];m(document.documentElement,this.options.jsClass);this.wrapperEl=a.replace("#","");if(document.getElementById(this.wrapperEl))this.wrapper=document.getElementById(this.wrapperEl);else if(document.querySelector(this.wrapperEl))this.wrapper=document.querySelector(this.wrapperEl);
else throw Error("The nav element you are trying to select doesn't exist");this.wrapper.inner=u(this.wrapper);f=this.options;d=this.wrapper;this._init(this)};r.prototype={destroy:function(){this._removeStyles();q(d,"closed");q(d,"opened");d.removeAttribute("style");d.removeAttribute("aria-hidden");d=null;h(window,"resize",this,!1);h(document.body,"touchmove",this,!1);h(e,"touchstart",this,!1);h(e,"touchend",this,!1);h(e,"mouseup",this,!1);h(e,"keyup",this,!1);h(e,"click",this,!1);f.customToggle?e.removeAttribute("aria-hidden"):
e.parentNode.removeChild(e)},toggle:function(){!0===n&&(p?(q(d,"opened"),m(d,"closed"),l(d,{"aria-hidden":"true"}),f.animate?(n=!1,setTimeout(function(){d.style.position="absolute";n=!0},f.transition+10)):d.style.position="absolute",p=!1,f.close()):(q(d,"closed"),m(d,"opened"),d.style.position=f.openPos,l(d,{"aria-hidden":"false"}),p=!0,f.open()))},handleEvent:function(a){a=a||window.event;switch(a.type){case "touchstart":this._onTouchStart(a);break;case "touchmove":this._onTouchMove(a);break;case "touchend":case "mouseup":this._onTouchEnd(a);
break;case "click":this._preventDefault(a);break;case "keyup":this._onKeyUp(a);break;case "resize":this._resize(a)}},_init:function(){m(d,"nav-collapse");m(d,"closed");n=!0;p=!1;this._createToggle();this._transitions();this._resize();k(window,"resize",this,!1);k(document.body,"touchmove",this,!1);k(e,"touchstart",this,!1);k(e,"touchend",this,!1);k(e,"mouseup",this,!1);k(e,"keyup",this,!1);k(e,"click",this,!1);f.init()},_createStyles:function(){g.parentNode||(g.type="text/css",document.getElementsByTagName("head")[0].appendChild(g))},
_removeStyles:function(){g.parentNode&&g.parentNode.removeChild(g)},_createToggle:function(){if(f.customToggle){var a=f.customToggle.replace("#","");if(document.getElementById(a))e=document.getElementById(a);else if(document.querySelector(a))e=document.querySelector(a);else throw Error("The custom nav toggle you are trying to select doesn't exist");}else a=document.createElement("a"),a.innerHTML=f.label,l(a,{href:"#","class":"nav-toggle"}),"after"===f.insert?d.parentNode.insertBefore(a,d.nextSibling):
d.parentNode.insertBefore(a,d),e=a},_preventDefault:function(a){a.preventDefault?(a.preventDefault(),a.stopPropagation()):a.returnValue=!1},_onTouchStart:function(a){a.stopPropagation();this.startX=a.touches[0].clientX;this.startY=a.touches[0].clientY;this.touchHasMoved=!1;h(e,"mouseup",this,!1)},_onTouchMove:function(a){if(10<Math.abs(a.touches[0].clientX-this.startX)||10<Math.abs(a.touches[0].clientY-this.startY))this.touchHasMoved=!0},_onTouchEnd:function(a){this._preventDefault(a);if(!this.touchHasMoved)if("touchend"===
a.type){this.toggle(a);var b=this;d.addEventListener("click",b._preventDefault,!0);setTimeout(function(){d.removeEventListener("click",b._preventDefault,!0)},f.transition+100)}else{var c=a||window.event;3!==c.which&&2!==c.button&&this.toggle(a)}},_onKeyUp:function(a){13===(a||window.event).keyCode&&this.toggle(a)},_transitions:function(){if(f.animate){var a=d.style,b="max-height "+f.transition+"ms";a.WebkitTransition=b;a.MozTransition=b;a.OTransition=b;a.transition=b}},_calcHeight:function(){for(var a=
0,b=0;b<d.inner.length;b++)a+=d.inner[b].offsetHeight;a=".nav-collapse.opened{max-height:"+a+"px}";g.styleSheet?g.styleSheet.cssText=a:g.innerHTML=a},_resize:function(){"none"!==window.getComputedStyle(e,null).getPropertyValue("display")?(l(e,{"aria-hidden":"false"}),d.className.match(/(^|\s)closed(\s|$)/)&&(l(d,{"aria-hidden":"true"}),d.style.position="absolute"),this._createStyles(),this._calcHeight()):(l(e,{"aria-hidden":"true"}),l(d,{"aria-hidden":"false"}),d.style.position=f.openPos,this._removeStyles())}};
return new r(s,t)};
